import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const worksans = localFont(
  {
    src: './fonts/WorkSans-VariableFont_wght.ttf',
    display: 'swap',
    variable: '--font-work-sans',
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${worksans.className} min-h-screen`}>{children}</body>
    </html>
  );
}
